/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'azeez' at '18-9-13 下午1:38' with Gradle 2.14.1
 *
 * @author azeez, @date 18-9-13 下午1:38
 */
public class Library {
	public static void main(String arg[]){
		System.out.println("When there is a fire, commit and push");
	}
    public boolean someLibraryMethod() {
        return true;
    }
}
